### ISSUE TITLE
Allow someone to override the location of the package.json or bower.json

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/auditjs#113]
Some users might want to run `auditjs` on files in different locations. This may take some thought, as we scan the `node_modules` at least for the package.json approach, so we will need to either inform them that this should exist (we scan installed things). For Bower this is likely quite easy.

**Comment by ajurgenson55** [comment]
Not sure if the use case exists except in projects that have nested node_modules, but i don't think we should combine multiple node_modules reports as you wouldn't be able to tell where they're from since the occurrences are purls in IQ and OSS wouldn't tell you

Lots of effort that would open up a can of worms, additionally it will be covered by #122 for IQ
