### ISSUE TITLE
Ability to audit libraries that aren't in bower or package

### ISSUE THREAD

**Issue by roine** [sonatype-nexus-community/auditjs#34]
I have some libraries that are too old to be in npm or bower and would like to check their vulnerability.

It would be nice create a json file containing those libraries information, ie: 
```json
// additional.json
{ "use": [{"jquery": "1.0.1"}]}
```
Then in the shell
```shell
$ auditjs [-a|--add] additional.json
```
If the idea sounds good, I could dig into it.

**Comment by OSSIndex-Admin** [comment]
This is great! I think it is a great idea and am definitely keen.

In order to directly use your contribution Sonatype requests that you sign a CLA (Contributor License Agreement) which more or less grants Sonatype permission to use the code. The agreement is reasonably short.

http://www.sonatype.org/SonatypeCLA.pdf

If you are alright with this, you can send the signed document here: jhesse@sonatype.com

If you could then notify me that would be great, since I will probably not be informed directly.

If you cannot sign the agreement for whatever reason, I still like the idea and will see if I can fit it in sometime. I have many irons in the fire, though, so it will definitely come to fruition earlier if you have a chance, and I am always eager for the help and ideas!

**Comment by ajurgenson55** [comment]
Closing, we will be implementing file level scanning with IQ, and for OSSI i think we will be sticking to auditing installed packages
